# Generated by Django 5.2.4 on 2025-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vargachart',
            name='interpretation',
        ),
        migrations.AlterField(
            model_name='birthchart',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='birthchart',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='birthchart',
            name='timezone',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vargachart',
            name='chart_type',
            field=models.CharField(max_length=10),
        ),
    ]
