# Generated by Django 5.2.4 on 2025-07-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_vargachart_interpretation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vargachart',
            name='svg_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
